---
- name: Install DNF backend
  command:
    cmd: "dnf -y install python3-libdnf{% if ansible_pkg_mgr == 'dnf5' %}5{% endif %}"
  register: noobient_update_dnf_backend
  changed_when: ('Nothing to do' not in noobient_update_dnf_backend.stdout)

- name: Update DNF info and all OS packages
  dnf:
    name: '*'
    state: latest

- name: Install dnf-automatic
  dnf:
    name: dnf-automatic

- name: Enable applying updates
  ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: apply_updates
    value: 'yes'
    mode: '0644'

- name: Enable dnf-automatic
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true
