---
- name: Install DNF backend
  package:
    name: "python3-libdnf{% if ansible_pkg_mgr == 'dnf5' %}5{% endif %}"
    state: latest
    use: dnf

- name: Update DNF info and all OS packages
  dnf:
    name: '*'
    state: latest

- name: Install dnf-automatic
  dnf:
    name: dnf-automatic

- name: Enable applying updates
  ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: apply_updates
    value: 'yes'
    mode: '0644'

- name: Enable dnf-automatic
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true
